// Generated by tools/export_game_data.py from balance_sim.py and ASSET_MANIFEST.json.
class Gate {
  final int minimumLevel;
  final int count;
  const Gate(this.minimumLevel, this.count);
}

abstract final class Balance {
  static const version = '0.3';
  static const maxLevel = 38;
  static const rareMaxLevel = 10;
  static const startGold = 500.0;
  static const maxGold = 1e100;
  static const rareChance = 0.005;
  static const rareChanceLevels = <double>[0.005, 0.01, 0.02, 0.03, 0.04, 0.05];
  static const rareChancePrices = <double>[
    76900.0,
    3620000.0,
    516000000.0,
    244000000000.0,
    116000000000000.0,
  ];
  static const probabilities = <double>[
    0.95,
    0.93,
    0.91,
    0.89,
    0.87,
    0.85,
    0.82,
    0.79,
    0.76,
    0.73,
    0.7,
    0.67,
    0.64,
    0.61,
    0.58,
    0.55,
    0.52,
    0.49,
    0.46,
    0.43,
    0.4,
    0.38,
    0.36,
    0.34,
    0.32,
    0.3,
    0.28,
    0.26,
    0.24,
    0.22,
    0.2,
    0.18,
    0.16,
    0.14,
    0.12,
    0.1,
    0.08,
    0.05,
  ];
  static const salePrices = <double>[
    0.0,
    20,
    52.0,
    107.0,
    201.0,
    362.0,
    638.0,
    1130.0,
    2060.0,
    3900.0,
    7690.0,
    15700.0,
    32400.0,
    69500.0,
    155000.0,
    362000.0,
    895000.0,
    2300000.0,
    6170000.0,
    17400000.0,
    51600000.0,
    163000000.0,
    533000000.0,
    1820000000.0,
    6520000000.0,
    24400000000.0,
    95300000000.0,
    295000000000.0,
    954000000000.0,
    3240000000000.0,
    11600000000000.0,
    44300000000000.0,
    130000000000000.0,
    408000000000000.0,
    1390000000000000.0,
    5220000000000000.0,
    2.22e+16,
    1.11e+17,
    7.98e+17,
  ];
  static const enhanceCosts = <double>[
    10,
    12.0,
    15.0,
    19.0,
    24.0,
    30.0,
    38.0,
    56.0,
    103.0,
    195.0,
    384.0,
    785.0,
    1620.0,
    3480.0,
    7750.0,
    18100.0,
    44800.0,
    115000.0,
    308000.0,
    870000.0,
    2580000.0,
    8150000.0,
    26600000.0,
    91000000.0,
    326000000.0,
    1220000000.0,
    4760000000.0,
    14800000000.0,
    47700000000.0,
    162000000000.0,
    580000000000.0,
    2220000000000.0,
    6500000000000.0,
    20400000000000.0,
    69500000000000.0,
    261000000000000.0,
    1110000000000000.0,
    5550000000000000.0,
  ];
  static const rareProbabilities = <double>[
    0.7,
    0.65,
    0.6,
    0.55,
    0.5,
    0.45,
    0.4,
    0.35,
    0.3,
    0.25,
  ];
  static const rareMultipliers = <double>[
    1.0,
    1.2857142857142858,
    1.7802197802197803,
    2.6703296703296706,
    4.36963036963037,
    7.865334665334665,
    15.73066933066933,
    35.394005994005994,
    91.01315827030113,
    273.0394748109034,
    982.9421093192523,
  ];
  static const slotPrices = <double>[
    3840.0,
    25800000.0,
    12200000000.0,
    5800000000000.0,
    2610000000000000.0,
  ];
  static const negotiationPrices = <double>[
    4120.0,
    310000.0,
    34800000.0,
    13000000000.0,
    6480000000000.0,
  ];
  static const fees = <double>[0.25, 0.2, 0.15, 0.1, 0.05, 0.0];
  static const normalNames = <String>[
    "녹슨 검",
    "낡은 철검",
    "단조 철검",
    "넓은 철검",
    "기사 철검",
    "무쇠 검",
    "견습 강철검",
    "보병 강철검",
    "기사 강철검",
    "왕실 강철검",
    "강철 검",
    "미스릴 단검",
    "미스릴 장검",
    "미스릴 기사검",
    "미스릴 왕검",
    "미스릴 검",
    "새김 룬검",
    "쌍날 룬검",
    "수호 룬검",
    "룬 검",
    "그람",
    "용아검",
    "용익검",
    "용혈검",
    "용린 검",
    "레바테인",
    "순백 성검",
    "여명 성검",
    "심판 성검",
    "성검",
    "듀랜달",
    "홍옥 신화검",
    "제왕 신화검",
    "불멸 신화검",
    "신화의 검",
    "엑스칼리버",
    "별의 태초검",
    "태초의 검",
    "종언의 검",
  ];
  static const gates = <int, Gate>{
    10: Gate(5, 1),
    15: Gate(10, 1),
    20: Gate(15, 1),
    25: Gate(20, 2),
    30: Gate(25, 2),
    35: Gate(30, 2),
  };
  static const protectionChances = <double>[0.0, 0.25, 0.5, 0.9];
  static const protectionRates = <double>[0.0, 0.06, 0.15, 0.35];
  static double protectionCost(int level, int option) {
    if (level == 0 || level >= maxLevel) return 0;
    final scale = level >= 31
        ? .3
        : level >= 26
        ? .6
        : 1;
    return salePrices[level] * protectionRates[option] * scale;
  }
}
